// Game Data - All game-related data consolidated in one file

// Main game data object
const gameData = {
    truthOrDareHistory: []
};

// Truth or Dare game data - Advanced Edition
const truthOrDareData = {
    truths: [
        "What's a fantasy you've been too embarrassed to share until now?",
        "Have you ever questioned our compatibility seriously?",
        "What's a secret desire you would only trust me with?",
        "Tell me about a moment you lost attraction for me—even briefly.",
        "Have you lied to spare my feelings about something important?",
        "What's the wildest thing you'd be willing to try with me sexually?",
        "What insecurity in our relationship do you hide from me?",
        "If you could change something fundamental about me, would you? What?",
        "What's a taboo or 'off-limits' topic that secretly interests you?",
        "Have you ever thought about cheating, even in passing?",
        "What's the harshest criticism you've ever wanted to give me?",
        "Describe a jealousy you've pretended not to feel.",
        "When did you last have a vivid sexual fantasy that wasn't about me?",
        "What is your furthest line—what's something you refuse to try, no matter what?",
        "What's the riskiest thing you'd be willing to do in public?",
        "What's a past relationship experience you secretly miss?",
        "Have you ever fantasized about us inviting someone else?",
        "What's the biggest mistake you think I've made in our relationship?",
        "What do you find most intimidating or overwhelming about me?",
        "If I wasn't in your life today, what would you immediately do differently?",
        "What's a memory you regret most in our relationship?",
        "Have you ever felt ashamed after intimacy with me? Why?",
        "If you could spend one 'no-limits' day doing anything, what would it be?",
        "What is your most controversial personal opinion—about us or in general?",
        "Have you ever doubted your love for me?",
        "Is there something I do in bed that you don't actually like?",
        "What's the most rebellious thing you've ever done with a partner?",
        "When have you faked emotions with me (joy, excitement, arousal, love)?",
        "What is a deeper craving you feel I don't understand?",
        "What scares you most about how strong our connection could get?",
        "Have you ever felt emotionally distant but kept it hidden?",
        "What's the biggest insecurity you have when we're intimate?",
        "What's a major turn-off you never told me about?",
        "What do you envy about other couples?",
        "Would you stay with me if we couldn't have sex for a year?",
        "What's a decision I made that made you question us?",
        "What do you think would end our relationship if we're not careful?",
        "Has someone else ever made you feel something you didn't expect?",
        "Have you ever imagined your life with someone else?",
        "What's something you're afraid I'd judge you for if I knew the full story?",
        "Which ex are you most tempted to check on even now?",
        "When do I make you feel most insecure?",
        "If we took a break, what would you truly want to explore?",
        "Have you ever compared me to your ideal partner in your head?",
        "What would you change about our sex life right now?",
        "What's something I've never asked you that you wished I would?",
        "What's something you've lied to yourself about just to stay happy?",
        "Have you ever stayed in the relationship for comfort over passion?",
        "Are you fully emotionally vulnerable with me?",
        "What's the one question you hope I never ask?",
        "What's one experience you've hidden from your past?",
        "What do you believe about love that I probably don't know?",
        "Have I ever disappointed you sexually?",
        "What's the one part of the relationship you feel alone in?",
        "What's your real opinion about our chemistry?",
        "Have you ever exaggerated our connection to someone else?",
        "What kind of temptation is hardest for you to resist?",
        "What's your darkest relationship fear?",
        "What's one thing you would only try if I really encouraged you?",
        "Do you ever worry this relationship will end like a past one?"
    ],
    dares: [
        "Share your most explicit fantasy out loud—no holding back.",
        "Recreate an unforgettable 'first time' experience in your own way.",
        "Strip to your underwear, grab an ice cube, and use it for a sensual massage.",
        "Send your partner a bold, sensual audio message.",
        "Give a five-minute lap dance—be as flirty as possible.",
        "Act out a 'forbidden wish' scenario for five minutes.",
        "Write down your three 'dirtiest thoughts' and trade papers.",
        "Blindfold me and do what you want (within consent & comfort).",
        "Read an erotic story aloud while sitting close.",
        "Kiss all the way down your partner's body—skip only one place.",
        "Do a striptease while maintaining eye contact.",
        "Whisper your deepest craving into my ear—slowly.",
        "Roleplay: Be someone you'd like to experience a fantasy with.",
        "Play your sexiest playlist and sync your movement with the beat.",
        "Let your partner tie your hands loosely and tease you.",
        "Ask a question so explicit it makes both of you blush.",
        "Choose a sex position you've never tried—try it tonight.",
        "Take turns saying one word each to describe a steamy scene.",
        "Use a feather (or fingers) to caress your partner while they stay silent.",
        "Put on a shirt with no underwear for the next 20 minutes.",
        "Take a photo of a body part your partner finds sexy (for them only).",
        "Pick up a household object and make it sexy (No explanation).",
        "Whisper everything you want to do to your partner tonight.",
        "Write a one-sentence erotic story and read it in your best voice.",
        "Do a sensual body trace with your lips only.",
        "Give your partner five commands—they must follow all.",
        "Create a new kissing technique and get rated out of 10.",
        "Give a slow-motion kiss—take 30 seconds to move in.",
        "Turn off the lights and play 'guess where I kiss.'",
        "Touch your partner gently while describing your favorite scene with them.",
        "Act like a seductress/seducer for the next five minutes.",
        "Set the scene: Pretend you're strangers meeting at a bar.",
        "Let your partner use their hands to draw imaginary tattoos on you.",
        "Do an erotic role-play as two characters from fiction.",
        "Lightly restrain your partner and deliver kisses under strict control.",
        "Spell your name with kisses on their body.",
        "Use food (like whipped cream or chocolate) creatively and delicately.",
        "Play 'Simon Says' but only with flirty instructions.",
        "Have one person blindfolded, the other completely in charge (safely).",
        "Sit on your partner's lap and whisper for 5 full minutes.",
        "Exchange 10 kisses in 10 different places.",
        "Try a silent make-out challenge—no speaking allowed.",
        "Kiss your partner like it's the last time.",
        "Invent a new name for each other's private parts and announce them.",
        "Roleplay: You're long-lost lovers reuniting after years apart.",
        "Pick one position and hold it while making out for 1 minute.",
        "Give a massage only using your lips and breath.",
        "Choose a code word that means 'turn up the heat'.",
        "Try an 'ice and fire' game—mix light touch and sensual contrast.",
        "Set a timer for 2 minutes and tease each other without kissing.",
        "Close your eyes and let your partner surprise you with 3 touches.",
        "Let your partner describe their ultimate night, action by action, as you listen.",
        "Use nothing but touch from elbows down to explore your partner's body.",
        "Eye contact challenge—who breaks first during an intense stare?",
        "Sit back-to-back and tell each other what makes you feel desired.",
        "Act out a steamy dream you once had about each other.",
        "Both partners write down a dare anonymously & draw—you both do them.",
        "Try a daring kiss in front of a mirror—watch it happen.",
        "Pick a random surface in your home and create a memory on it.",
        "Plan your own erotic improv: no talking, just moving, for 3 minutes."
    ]
};

// Never Have I Ever statements
const neverHaveIEverData = [
    "Never have I ever pretended to be asleep to avoid a late-night conversation.",
    "Never have I ever secretly re-read old messages from you to feel closer.",
    "Never have I ever dreamt about marrying someone famous.",
    "Never have I ever lied about loving a gift you gave me.",
    "Never have I ever Googled \"is this normal in a relationship?\".",
    "Never have I ever planned an entire future vacation in my head without telling you.",
    "Never have I ever used a pet name for you in public and regretted it instantly.",
    "Never have I ever snooped through your social media \"likes.\"",
    "Never have I ever rehearsed what I'd say in an argument—alone in the shower.",
    "Never have I ever stalked an ex's profile after we became official.",
    "Never have I ever imagined our wedding playlist.",
    "Never have I ever been jealous of your best friend's partner.",
    "Never have I ever tried to guess your phone passcode.",
    "Never have I ever planned a surprise for you that totally backfired.",
    "Never have I ever forgotten an anniversary and covered it up.",
    "Never have I ever practised kissing on my hand before an early date.",
    "Never have I ever lied about liking a movie just because you did.",
    "Never have I ever cried during a rom-com and blamed allergies.",
    "Never have I ever flirted to get a free drink while we were together.",
    "Never have I ever checked your location without telling you.",
    "Never have I ever pretended to know sports rules to impress you.",
    "Never have I ever texted an ex after a fight with you.",
    "Never have I ever kept a ticket stub from our first outing.",
    "Never have I ever faked confidence during an intimate moment.",
    "Never have I ever Googled \"cute ways to apologize.\"",
    "Never have I ever skipped a workout to stay in bed with you.",
    "Never have I ever told my friends embarrassing details about our date night.",
    "Never have I ever had a crush on a fictional character stronger than a real one.",
    "Never have I ever planned baby names in my notes app.",
    "Never have I ever bought something just because it's your favorite color.",
    "Never have I ever pretended to laugh at your joke even when I didn't get it.",
    "Never have I ever practiced a \"sexy walk\" before seeing you.",
    "Never have I ever compared our relationship to a celebrity couple's.",
    "Never have I ever sent a risky text and then put my phone away in panic.",
    "Never have I ever tried to read your mind during a silent car ride.",
    "Never have I ever imagined us as parents during a random moment.",
    "Never have I ever watched an entire show without you after promising to wait.",
    "Never have I ever considered eloping instead of a big wedding.",
    "Never have I ever said \"I love you\" first and wished I'd waited.",
    "Never have I ever lied about being busy just to get alone time.",
    "Never have I ever bookmarked engagement rings online.",
    "Never have I ever laughed so hard in bed that mood was ruined.",
    "Never have I ever worried I was the \"reach\" in this relationship.",
    "Never have I ever thought about moving to another city for you.",
    "Never have I ever kissed someone in the rain—movie-style.",
    "Never have I ever answered a question with \"fine\" when it wasn't.",
    "Never have I ever googled \"how to spice things up\" at 2 a.m.",
    "Never have I ever daydreamed about our retirement together.",
    "Never have I ever used a romantic quote and pretended it was mine.",
    "Never have I ever worn your clothes all day just to feel close.",
    "Never have I ever doubted our relationship and kept silent about it.",
    "Never have I ever hidden snacks from you to avoid sharing.",
    "Never have I ever told a white lie about your cooking.",
    "Never have I ever re-read an old love letter and cried.",
    "Never have I ever felt butterflies on our anniversary like the first date.",
    "Never have I ever wished you had my hobby so we could share it.",
    "Never have I ever imagined how you'd look in a decade.",
    "Never have I ever made a playlist that secretly tells our love story.",
    "Never have I ever posted a couple photo mainly to make someone jealous.",
    "Never have I ever thought, \"This might be the person I grow old with,\" and smiled."
];

// Love Coupons rewards
// Enhanced Quiz Questions
const enhancedQuizQuestions = {
    easy: [
        {
            question: "What's my favorite color?",
            category: "Basics",
            points: 1
        },
        {
            question: "What's my favorite food or cuisine?",
            category: "Preferences",
            points: 1
        },
        {
            question: "What time do I usually go to bed?",
            category: "Habits",
            points: 1
        },
        {
            question: "What's my favorite season of the year?",
            category: "Preferences",
            points: 1
        },
        {
            question: "What's my preferred way to spend a lazy Sunday?",
            category: "Lifestyle",
            points: 1
        },
        {
            question: "What type of music do I listen to most?",
            category: "Entertainment",
            points: 1
        },
        {
            question: "What's my favorite type of movie or TV show?",
            category: "Entertainment",
            points: 1
        },
        {
            question: "What's my favorite social media platform?",
            category: "Technology",
            points: 1
        }
    ],
    medium: [
        {
            question: "What was I most afraid of as a child?",
            category: "Personal History",
            points: 2
        },
        {
            question: "What's a skill I've always wanted to learn but haven't yet?",
            category: "Aspirations",
            points: 2
        },
        {
            question: "What's my biggest pet peeve in relationships?",
            category: "Relationship Insights",
            points: 2
        },
        {
            question: "What would I do if I won the lottery tomorrow?",
            category: "Hypotheticals",
            points: 2
        },
        {
            question: "What's the most romantic gesture someone could do for me?",
            category: "Romance",
            points: 2
        },
        {
            question: "What's something I'm secretly insecure about?",
            category: "Deep Personal",
            points: 2
        },
        {
            question: "What career would I pursue if money wasn't a factor?",
            category: "Dreams",
            points: 2
        },
        {
            question: "What's my love language (how I prefer to receive love)?",
            category: "Relationship Psychology",
            points: 2
        },
        {
            question: "What's a childhood memory that still makes me smile?",
            category: "Memories",
            points: 2
        },
        {
            question: "What quality do I admire most in other people?",
            category: "Values",
            points: 2
        }
    ],
    hard: [
        {
            question: "What's my deepest fear about our future together?",
            category: "Deep Relationship",
            points: 3
        },
        {
            question: "What's something I've never told anyone else but you?",
            category: "Intimate Secrets",
            points: 3
        },
        {
            question: "What would I regret most if I died tomorrow?",
            category: "Life Philosophy",
            points: 3
        },
        {
            question: "What's the exact way I like to be comforted when I'm really upset?",
            category: "Emotional Needs",
            points: 3
        },
        {
            question: "What's my biggest internal struggle that I don't often talk about?",
            category: "Inner Conflicts",
            points: 3
        },
        {
            question: "What specific thing about me changed after we started dating?",
            category: "Relationship Impact",
            points: 3
        },
        {
            question: "What's my most irrational belief or superstition?",
            category: "Quirks",
            points: 3
        },
        {
            question: "What would I want my legacy to be?",
            category: "Life Purpose",
            points: 3
        },
        {
            question: "What's the specific way I show love when I'm stressed or busy?",
            category: "Complex Emotions",
            points: 3
        },
        {
            question: "What's something I judge others for but do myself?",
            category: "Self-Awareness",
            points: 3
        }
    ]
};

// Motivational messages for quiz results
const motivationalMessages = {
    excellent: "Incredible! You two are perfectly in sync. Your connection is truly remarkable! 💕",
    great: "Excellent! You know each other very well. Your bond is strong and beautiful! ✨",
    good: "Great job! You're learning more about each other. Keep communicating and growing together! 🌱",
    fair: "Good start! There's so much more to discover about each other. Keep exploring! 🗺️",
    needs_work: "Every relationship is a journey of discovery. Use this as a chance to learn and grow closer! 💖"
};

// Export all data for use in other files
if (typeof module !== 'undefined' && module.exports) {
    // Node.js environment
    module.exports = {
        gameData,
        truthOrDareData,
        kissData,
        neverHaveIEverData,
        enhancedQuizQuestions,
        motivationalMessages,
        cardGameData
    };
}

// Card Game Data - 9 Categories with 60 Cards Each
const cardGameData = {
    emotionalIntimacy: [
        "What does love feel like to you?",
        "What makes you feel most safe with me?",
        "How do you like to be comforted when you're upset?",
        "What's a moment with me you'll always cherish?",
        "When was the last time you felt truly understood?",
        "What's something you're afraid to admit to me?",
        "What do I do that makes you feel deeply cared for?",
        "If you could relive one day with me, which would it be?",
        "What's something you wish I said to you more often?",
        "What do you need when you're hurt emotionally?",
        "When did you last feel truly connected to me?",
        "What does emotional vulnerability mean to you?",
        "How do you know I love you?",
        "How can I show I'm listening better?",
        "What's a memory that still makes you smile?",
        "When do you feel most appreciated by me?",
        "What scares you about our relationship?",
        "What's your love language and how do I fulfill it?",
        "What makes you feel unwanted or distant?",
        "What's something I'm doing well in our relationship?",
        "When do you feel most proud to be with me?",
        "What's one trait of mine you deeply love?",
        "What can I do to emotionally support you better?",
        "How do you feel after we argue?",
        "How can we resolve conflict in a more loving way?",
        "What kind of emotional connection do you crave most?",
        "What's your biggest emotional wound from past relationships?",
        "What do we do that makes you feel like a team?",
        "When have you felt closest to me in the last month?",
        "How would you describe our emotional connection?",
        "When do you feel seen by me?",
        "What role does emotional intelligence play in love?",
        "What's one thing no one else knows about you?",
        "What helps you open up emotionally?",
        "What frustrates you emotionally in a relationship?",
        "What is something small I do that melts your heart?",
        "How can we grow stronger emotionally together?",
        "What does 'being emotionally naked' mean to you?",
        "When do you need space, and how should I respect it?",
        "What's something you're currently healing from?",
        "What does emotional intimacy look like on a bad day?",
        "What part of my personality comforts you the most?",
        "Have I ever made you feel insecure? How?",
        "How do you feel when I cry or am vulnerable?",
        "What's something you thanked me for silently?",
        "What's a moment that challenged you to trust me deeper?",
        "What emotional risks have you taken with me?",
        "What's your earliest memory of feeling love?",
        "How do you recharge emotionally?",
        "When do you feel most emotionally drained?",
        "What topics are difficult for you to talk about?",
        "How do you process emotional pain?",
        "What's one thing you admire about how I express emotions?",
        "What boundaries help protect our emotional connection?",
        "How can I help you trust love more deeply?",
        "When do I make you feel emotionally disconnected?",
        "What's your deepest emotional need?",
        "What song or movie reminds you of our connection?",
        "What's your emotional superpower in this relationship?",
        "When you're overwhelmed, how would you like me to support you?"
    ],
    
    sexualIntimacy: [
        "What is your biggest turn-on?",
        "Describe a fantasy you've never shared.",
        "What does great sex mean to you?",
        "How do you like to be touched?",
        "What outfit would you love to see me in?",
        "What is something new you want to try together in bed?",
        "Name a place you want to have sex that we haven't tried.",
        "Is there a sex scene in a movie that turns you on—what is it?",
        "What's the most romantic thing I could do to set the mood?",
        "Do you prefer slow or passionate kisses?",
        "What's your favorite time of day for intimacy?",
        "What song would be our perfect 'bedroom playlist' track?",
        "Is there a part of your body you wish I touched more?",
        "What compliment turns you on the most?",
        "Do you enjoy talking dirty? Why or why not?",
        "Are you more into teasing or pleasing?",
        "What's a position you want to try?",
        "What's the hottest thing I've ever done to you?",
        "Describe your ideal date night that ends in sex.",
        "Do you have a secret sexual fantasy about me?",
        "Where do you love to be kissed?",
        "How do you feel about toys in the bedroom?",
        "Do you prefer lights on or off?",
        "What's a sensual scent that excites you?",
        "What type of touch relaxes you before sex?",
        "Share something that instantly puts you in the mood.",
        "What's one word you wish I'd whisper in your ear?",
        "Is there a sensual massage you'd love to receive?",
        "What makes you feel sexy?",
        "Would you rather give or receive oral?",
        "What's a spontaneous place you'd hook up?",
        "What's a sexual limit you never want to cross?",
        "How can I make you feel more desired?",
        "What outfit would you pick for a sexy photoshoot?",
        "Would you rather dominate or submit?",
        "What's a small thing I do that turns you on?",
        "How was your first sexual experience?",
        "What do you think about during foreplay?",
        "Where is your most sensitive spot?",
        "How do you feel about shower sex?",
        "Would you try sexting or video chat for intimacy?",
        "Do you enjoy role play—if so, what's your favorite?",
        "What's one thing we should never stop doing in bed?",
        "Do you like being surprised or planned with intimacy?",
        "How do you feel after we make love?",
        "What sexy nickname do you want from me?",
        "What's the wildest place you've ever fantasized about us?",
        "How do you like me to initiate intimacy?",
        "Is there something you've been afraid to ask for?",
        "What's your favorite way to be seduced?",
        "How long does your perfect foreplay last?",
        "What food would you want incorporated into foreplay?",
        "Describe a dream 'morning after.'",
        "What do you do when you want me badly?",
        "How comfortable do you feel talking about sex?",
        "What's your best sexual memory with me?",
        "What's something sexy you've wanted to say but haven't?",
        "How can we make our love life even better?",
        "Is there a forbidden fantasy you want to share?",
        "What's your definition of true sexual intimacy?"
    ],
    
    afterDark: [
        "Share your wildest intimate dream about us.",
        "Whisper the naughtiest thought you've had about me today.",
        "Flash me your sexiest look.",
        "Text me something you'd only say after midnight.",
        "Describe, in detail, your favorite way for me to touch you.",
        "Confess a secret fantasy you want to try together.",
        "Send me a sultry selfie (real or imagined).",
        "Kiss me in the spot you find most irresistible.",
        "Give me a three-word dirty whisper.",
        "Dare: Try a new kissing style with me for 2 minutes.",
        "Imitate the sexiest movie scene you know.",
        "Invent a secret code word for 'let's get naked.'",
        "Describe a forbidden place where you want us to get frisky.",
        "What's a song that makes you want me right now?",
        "Give me a lap dance—no music allowed.",
        "Dare: Wear nothing but a blanket for the next round.",
        "Complete this sentence: 'I want you to…'",
        "Suggest a bedroom game we've never played.",
        "Seductively trace a word onto my skin—let me guess it.",
        "Share your most daring 'public' fantasy.",
        "Read a page from an erotic book out loud (or imagine one).",
        "Describe your favorite part of my body, and why.",
        "Let's see who can make the other blush first.",
        "Dare: Send a flirty text to my phone right now.",
        "What's your favorite 'after dark' activity for us?",
        "Design a sexy dare for me (your pick).",
        "Use only body language to tell me what you want.",
        "Whisper something you want me to do tonight.",
        "Strip down to your favorite sleepwear—or less.",
        "Close your eyes: let me surprise you with a gentle touch.",
        "Share a secret desire about a future getaway.",
        "Pick a random object and make it part of our fun (safely!).",
        "What would our code name be if we were erotic spies?",
        "Imagine an 'after dark' alter ego for us—describe them!",
        "Play a round of physical Truth or Dare—with no 'truths.'",
        "If you could rename me for tonight, what would it be?",
        "What's one thing I could do right now to drive you crazy?",
        "Dare: Kiss me somewhere you've never kissed before.",
        "What's the hottest time of day for 'us' and why?",
        "Invent a scandalous couple's nickname for us.",
        "Suggest a new word for 'turned on.'",
        "Dare: Make up a sexy bedtime story about us.",
        "How would you convince me to skip work for a day in bed?",
        "Play: Lie on the bed, let me trace a path with my fingertips.",
        "What's your most memorable dream involving me?",
        "Pick a trigger word—every time I say it, kiss me.",
        "If we had our own 'after dark' emoji, what would it look like?",
        "Dare: Give me a 60-second slow kiss tour—lips last.",
        "Share your earliest memory of wanting to be close to me.",
        "What's the boldest question you wish I'd ask you?",
        "Dare: Reenact your favorite flirty move.",
        "What 'naughty' compliment do you wish I'd give you?",
        "If tonight had a theme, what would it be?",
        "Name a song that sets the perfect mood for us.",
        "Share a one-liner that always gets you in the mood.",
        "Describe, step by step, your idea of the perfect sexy surprise.",
        "Dare: Draw a heart somewhere on me—using any part you want.",
        "What's your favorite time to snuggle naked?",
        "What's the most unexpected thing about our chemistry?",
        "Make up a sexy challenge for next date night."
    ],
    
    affectionRomance: [
        "Describe the first moment you realized you loved me.",
        "What small gesture from me always makes your day brighter?",
        "Share something adorable you've noticed about me recently.",
        "What is your favorite way for me to say 'I love you'?",
        "Write a short, sweet note to read to me now.",
        "What is the cutest nickname you've ever wanted to give me?",
        "How would you plan our perfect romantic evening at home?",
        "What's your favorite memory of us just being silly or playful?",
        "Describe how you feel when you hold my hand.",
        "What does the word 'us' mean to you?",
        "Name one thing I do that makes you feel deeply loved.",
        "If we had a signature couple's dance, what would it look like?",
        "What's a romantic movie scene that reminds you of us?",
        "What song best tells the story of our relationship?",
        "Tell me your favorite way to cuddle.",
        "What's your favorite affectionate compliment to receive from me?",
        "Describe an ideal lazy morning spent together.",
        "If you could wake up anywhere with me, where would it be?",
        "Share a moment you've felt totally accepted by me.",
        "What is one thing you wish I'd do more often to show I care?",
        "Compose a short love poem dedicated to us.",
        "Tell me what you cherish most about our kisses.",
        "When do you feel most at peace with me?",
        "What smell, touch, or sound reminds you of our love?",
        "List three things about us that are totally unique.",
        "Complete: 'Loving you is like…'",
        "What does my smile do to your heart?",
        "Describe the sweetest gift I've ever given you.",
        "How would you surprise me on a random day, just because?",
        "What is your favorite love story (fictional or real) and why?",
        "How do you like to be held when you're feeling down?",
        "Share something you want us to experience for the first time together.",
        "What's your favorite way I say your name?",
        "If you could send me a postcard from your heart, what would it say?",
        "What romantic holiday would you invent for us?",
        "When do you feel most supported by me?",
        "Tell me a single word that captures your love for me.",
        "How does our love make you feel brave?",
        "What's your idea of the perfect romantic getaway?",
        "Name a little habit of mine you think is adorable.",
        "What's the most beautiful thing about loving you?",
        "Describe the cutest couple tradition you want us to create.",
        "If you could make a wish for us, what would it be?",
        "Write or say a single line that melts your heart when you hear it from me.",
        "Share the first thing you noticed about me that made you smile.",
        "What part of our daily life together feels most like a fairytale?",
        "How would you describe 'our story' to a friend?",
        "What is the best compliment you've ever received from me?",
        "Describe a fictional place where we could spend a romantic day.",
        "When do you most feel we are a team?",
        "What's a romantic tradition from any culture you'd love to try?",
        "If you had to choose a 'couple's crest' for us, what would it look like?",
        "What's a quote or lyric that feels like it was meant for us?",
        "Tell me how I make your ordinary days extraordinary.",
        "What makes you excited about our future together?",
        "How does our love inspire you to be your best?",
        "Describe what 'happily ever after' looks like with me.",
        "Share the moment you most wanted to freeze in time with me.",
        "When do you feel most adored by me?",
        "What is one dream you hope we accomplish together?"
    ],
    
    communicationTrust: [
        "What's something you wish I asked you more often?",
        "How would you describe our communication style?",
        "What's one thing you find hard to say to me, and why?",
        "When do you feel most listened to by me?",
        "How can we both be better about apologizing?",
        "What was the last silly argument we had, and what did you learn from it?",
        "What makes apologizing easy—or hard—for you?",
        "How do you recognize when I'm really listening?",
        "When was the last time you felt misunderstood?",
        "What's the best way for me to comfort you during a conflict?",
        "What's a subject we avoid that you'd like to discuss more?",
        "What body language tells you I'm interested in your feelings?",
        "What's a communication habit you want us to improve?",
        "When do you feel safest telling me the truth?",
        "What's a difficult truth about yourself you've shared with me?",
        "When have you held back because you were afraid to upset me?",
        "What do you appreciate most about how I handle disagreements?",
        "How do you show me you trust me?",
        "What's a promise I made that meant a lot to you?",
        "How do you know I'm being honest with you?",
        "What does 'total honesty' look like in our relationship?",
        "When are you tempted to withhold your true feelings?",
        "What's a misunderstanding between us you still think about?",
        "How do you prefer to be approached during tense moments?",
        "What's a sign that it's time for us to have a heart-to-heart?",
        "What's your favorite way to resolve a conflict?",
        "What makes you feel unappreciated or unheard?",
        "How do you know when I need space?",
        "What's a communication challenge you've overcome together?",
        "How do you want me to handle your secrets?",
        "What's the hardest question you've ever asked me?",
        "When did you feel most proud of us for working through something tough?",
        "How do you like to 'check in' emotionally?",
        "What's a mistake you've learned the most from?",
        "When do you find it easy to forgive?",
        "What makes you trust my judgment?",
        "How can we create a better habit for tough conversations?",
        "What's the most difficult word to say in a relationship?",
        "How do you express that you're hurt or upset?",
        "What's one thing I do that helps you open up?",
        "If you could change one thing about how we talk about the future, what would it be?",
        "What signals to you that I'm keeping something in?",
        "How can we be better 'listeners' for each other?",
        "What's a nonverbal way you show love or support?",
        "What does 'fair fighting' mean to you?",
        "When do you know our trust is strongest?",
        "What's something personal you've never told anyone but me?",
        "How does it feel when we work through an argument?",
        "What's the best outcome you hope for when we disagree?",
        "How can I help you feel safer sharing your worries?",
        "What question are you afraid to ask me?",
        "When have we surprised ourselves by communicating well?",
        "How do we show gratitude for each other's honesty?",
        "What's one thing you hope never changes about how we connect?",
        "What would help you feel safer being vulnerable?",
        "How do you prefer to reconnect after a disagreement?",
        "What role does laughter play in our communication?",
        "How would you define 'respect' in conversation?",
        "What's the biggest risk you've taken in opening up to me?",
        "How can we set an example of trust for others?"
    ],
    
    relationshipGoals: [
        "Where do you see us in five years?",
        "What's one new tradition you'd like to build together?",
        "Describe your dream home and where it would be.",
        "What does our ideal future look like to you?",
        "How do you imagine spending our retirement years?",
        "What are three bucket-list experiences you want to share?",
        "How do you hope our relationship evolves over time?",
        "What is your vision for our family (kids, pets, etc.)?",
        "What career dreams do you want me to support you in?",
        "How can we balance personal and shared ambitions?",
        "What's one skill you want us to learn together?",
        "How do you want to celebrate our big milestones?",
        "Where would you love to travel with me someday?",
        "What steps can we take to support each other's growth?",
        "How would we handle major life changes together?",
        "Do you see us moving somewhere new in the future?",
        "What financial goals should we set as a couple?",
        "How do you picture our 'perfect' weekend in the future?",
        "What small thing could we start doing now to help our future?",
        "How do you want to handle disagreements as we grow?",
        "What legacy do you hope we create together?",
        "What values are most important for our future?",
        "How can we keep romance alive in the long term?",
        "What does 'success' look like for us as a couple?",
        "How will we celebrate our next major accomplishment?",
        "Would you rather plan everything in detail, or be spontaneous?",
        "What projects would you like us to start together?",
        "Where do you want to be living in five years?",
        "What new hobbies or activities should we try as a couple?",
        "How do you want to track and celebrate our goals?",
        "What's your dream trip for just the two of us?",
        "How can we keep learning from each other?",
        "Who are couples you admire and why?",
        "How often should we revisit and update our goals?",
        "What fears do you have about our future, and how can I help?",
        "How do you want us to resolve big decisions?",
        "What would make you feel fulfilled in our partnership?",
        "How can we support each other's friendships?",
        "What is the biggest dream you have for our life together?",
        "What traditions do you hope to pass down or create?",
        "How do you want to celebrate anniversaries in the future?",
        "What financial habits should we build as a team?",
        "When life gets overwhelming, what do you need from me?",
        "What opportunities would you like us to pursue as a couple?",
        "How can we ensure our relationship stays a priority?",
        "What's something we could do better together this year?",
        "How do you want us to give back or make a difference?",
        "What lifestyle changes do you hope to make together?",
        "What's a future adventure you'd like to plan?",
        "How should we handle challenges or setbacks as a team?",
        "What are your biggest hopes for us?",
        "How do you picture celebrating holidays through the years?",
        "What would you tell our future selves?",
        "How do you want to handle work-life balance as a couple?",
        "What helps you feel optimistic about our future?",
        "How will we check in on our relationship's progress?",
        "What's a big future decision you want to dream up together?",
        "How do you want us to communicate goals and dreams?",
        "What's your favorite vision of us in old age?",
        "What little things can we do now to nurture our dreams?"
    ],
    
    flirtyDares: [
        "Give your partner a romantic foot massage or back rub.",
        "Slow dance with me to a romantic song in the middle of the room.",
        "Whisper three heartfelt compliments into my ear.",
        "Kiss me like you mean it—for 30 seconds straight.",
        "Hold my hand and tell me your favorite memory of us.",
        "Dare: Send me a flirty text message using only emojis.",
        "Play a game of physical truth or dare with flirty challenges.",
        "Wear nothing but a blanket for the next round.",
        "Trace a word of love or desire on my skin and let me guess it.",
        "Give me a lap dance for one minute (no music needed).",
        "Write a short love poem and read it aloud to me.",
        "Use your elbows to eat a snack without using your hands.",
        "Blowing kisses to each other without speaking for 2 minutes.",
        "Take turns giving each other a 3-minute shoulder or neck massage.",
        "Whisper the naughtiest thing you want me to say right now.",
        "Kiss me somewhere you've never kissed before.",
        "Give me a slow kiss tour—start from my lips and wander down gently.",
        "Dare: Wear my favorite piece of your clothing for the rest of the game.",
        "Blindfold me and feed me different flavors—guess what they are.",
        "Send me a sexy selfie (or imagine one in your mind).",
        "Give me a hug and hold me close for one minute.",
        "Stroke my hair while telling me what you love about us.",
        "Make up a sexy bedtime story starring us.",
        "Pretend we're strangers meeting for the first time—flirt wildly.",
        "Dare: Freestyle rap about how much you love me.",
        "Kiss your favorite part of my body slowly and sensually.",
        "Slowly run your fingers down my arm and back up again.",
        "Hold eye contact with me as long as you can without smiling.",
        "Dare: Eat a popsicle as seductively as possible.",
        "Draw a heart on me using any part of your body.",
        "Whisper a secret desire into my ear.",
        "Share your favorite body part of mine and why.",
        "Make up a secret code word for 'let's get close' tonight.",
        "Dare: Wax poetic about how sexy I look right now.",
        "Stroke my cheek and say something you find irresistible about me.",
        "Give me a 10-second forehead kiss.",
        "Slow dance with me anywhere in the house—even without music.",
        "Pretend you're on a date with me at a dreamy restaurant.",
        "Describe to me your favorite way to be kissed.",
        "Dare: Text me a flirty message every 10 minutes for an hour.",
        "Give me a hug and whisper what you love most about me.",
        "Trace shapes or letters on my back and let me guess them.",
        "Kiss me on the neck softly and linger for a moment.",
        "Dare: Balance a piece of fruit on your head and walk around.",
        "Play 'hot potato' with a kiss—that means whoever gets it kisses!",
        "Give me a tickle attack and then a warm cuddle.",
        "Write a flirty message on a small note and hide it for me to find.",
        "Pretend you're writing a love letter to me, then read it aloud.",
        "Dare: Wear your clothes backward for the next 5 minutes.",
        "Offer me a gentle forehead kiss and hold my hand.",
        "Play a quick game of 'guess where I'm going to kiss next.'",
        "Share a sexy nickname you want me to use for you.",
        "Whisper a love secret you've never told me before.",
        "Dare: Act out a romantic movie scene with me.",
        "Trace your finger over my lips and tell me what you want to say.",
        "Kiss me on the cheek and count to ten before pulling away.",
        "Take turns describing a perfect date night you want with me.",
        "Whisper your biggest turn-on in my ear.",
        "Give me a massage using scented oil or lotion.",
        "Hold me close and tell me why you cherish our connection."
    ],
    
    funSilly: [
        "Make up a secret handshake for us—teach it to me.",
        "Invent a couple nickname for us and use it for an hour.",
        "If we were a famous duo, who would we be?",
        "Try to make me laugh without speaking.",
        "Draw a doodle of us as superheroes.",
        "Impersonate my favorite celebrity.",
        "Tell me your silliest childhood story.",
        "Make a silly face—hold it for 30 seconds.",
        "Give me a piggyback ride (or try!).",
        "Create a new dance move and name it after us.",
        "What food would you battle me with in a food fight?",
        "Battle in a staring contest—winner picks a prize.",
        "If our pet could talk, what would it say about us?",
        "Describe our relationship using only movie titles.",
        "Share your goofiest hidden talent.",
        "Play 'Truth or Dare'—only dares allowed!",
        "Try to rhyme everything you say for 5 minutes.",
        "Pick a random item and pretend it's a microphone—interview me!",
        "Make up a new holiday for us. What would we do?",
        "Attempt to recreate our first date dress code, but with silly accessories.",
        "Give me a 'good morning' song on the spot.",
        "What animal do you think I act like when I'm excited?",
        "Speak in a made-up language for two minutes.",
        "Play charades with our inside jokes.",
        "Describe a hilarious dream you've had.",
        "If our love had a mascot, what would it look like?",
        "Have a tongue twister battle—see who stumbles first.",
        "Tell me my 'superpower' in a fantasy world.",
        "Try to spell my name backwards—while dancing!",
        "Imagine us in a cartoon—what's our theme song?",
        "Have a funny hat fashion show (use whatever you have!).",
        "Invent your own couple dance challenge.",
        "Narrate what I'm doing as if you're a cheesy sports commentator.",
        "Eat a snack and act out a dramatic commercial for it.",
        "What would we sell if we had a silly business together?",
        "Try to wink without laughing—how long can you last?",
        "Pick a random word; work it into every answer for 10 minutes.",
        "Who is more likely to win a pie-eating contest? Prove it!",
        "If you could swap bodies with me for a day, what would you do first?",
        "Draw us as emojis—show me your masterpiece.",
        "Give a weather report in the silliest voice you can imagine.",
        "Come up with a joke about couples, tell it right now.",
        "Try giving me a pep talk as my 'coach' for date night.",
        "Challenge: Each time someone yawns, the other has to do 10 jumping jacks.",
        "Pretend you've bumped into 'future us'—what's our life like?",
        "Have a friendly thumb war—best out of three!",
        "Plan the world's goofiest vacation for us on the fly.",
        "Try to take the most awkward 'couple selfie' together.",
        "Challenge: Tell a story but each sentence must start with the next letter of the alphabet.",
        "If we could only communicate in memes, what would we say?",
        "Pretend you're a chef cooking up 'the recipe for our love.'",
        "Try moving across the room in slow motion—who does it best?",
        "What's a funny urban legend about couples you'd invent for us?",
        "Mix up our favorite snacks into a crazy 'couple combo'—who tries it first?",
        "Pretend to be each other for two minutes. Go!",
        "Tell me a pun involving our names.",
        "Describe our most ordinary habit in a super dramatic way.",
        "Laugh with me for no reason—who can last longer without stopping?",
        "Assign new, silly middle names for each other.",
        "Finish: 'Love is… like a ______'—but make it completely ridiculous!"
    ],
    
    sexualPositions: [
        "Try the classic **Missionary** position with deep eye contact.",
        "Switch to **Doggy Style**—see who likes the pace best.",
        "Explore **Cowgirl / Rider** with the receptive partner on top.",
        "Give **Reverse Cowgirl** a go—change the view, change the mood.",
        "Get adventurous with **Standing Face-to-Face**—lean on a wall for support.",
        "Enjoy **Spooning** for cozy, sensual connection.",
        "Challenge yourselves with **Lotus**—wrap your legs around each other as you sit.",
        "Experiment with **Edge-of-the-Bed**, one partner standing, the other lying back.",
        "Try the **Chair Ride**—one partner seated, the other straddling.",
        "Practice **Butterfly**—lying back near the edge, hips lifted.",
        "Get playful with **Scissors** position—both partners at angles.",
        "Try the **Bridge**—one lies back arched, other on top or kneeling.",
        "**Missionary with Legs on Shoulders**—for extra depth.",
        "Switch it up by doing **Doggy Style on the Couch**.",
        "Try the **Flatiron**—one partner lying face down, hips lifted.",
        "Go for **Reverse Spooning**, facing away but close.",
        "Get intimate with **Face-Sitting** or oral-focused positions.",
        "Experiment with **Standing Doggy Style**—bend over sturdy support.",
        "Try **Eye-to-Eye Sideways**—both lying on your sides.",
        "Explore the **X Marks the Spot**—crossed legs while straddling.",
        "Get creative with the **Lap Dance**—tease before going further.",
        "Attempt the **Crab Walk**—seated, facing each other, legs intertwined.",
        "**Kneeling Embrace**—both partners kneeling across from each other.",
        "Try the **On-Top Hug**—wrap your arms around your partner while straddling.",
        "Enjoy the **T-Position**—one lies straight, the other perpendicular.",
        "Try **The Wheelbarrow** (use pillows or cushions for comfort).",
        "Go for **Prone Bone**—one lies flat, other lies directly on top.",
        "**Seated Spoon**—both partners sitting side-by-side.",
        "Try the **Corkscrew**—lying on the side at an angle.",
        "**Standing Lift**—one partner picks the other up (carefully!).",
        "Go classic with **Missionary, Pillow Under Hips**.",
        "Explore the **Ballet Dancer**—standing, entwined legs.",
        "Try the **Rocking Horse**—one sits, other lies on top facing away.",
        "Have fun with the **Starfish**—one on their back, arms and legs wide.",
        "Try **Chair from Behind**—one sits, other straddles from the back.",
        "Explore **Kneeling Wheelbarrow**—one on all fours, other kneeling behind.",
        "**Crossed Ankles** in Missionary for a fresh twist.",
        "**Lap Pillow**—one partner rests their head on the other's lap for oral play.",
        "Try **Reverse Rider**—lying flat, partner sits facing feet.",
        "Go for **Face-to-Face Stand-Up Shower**.",
        "Enjoy the **Chair Straddle**—partner seated, other facing them.",
        "**Sitting Yab-Yum**—cross-legged and deeply connected.",
        "Try **Kneeling Over the Edge**—one kneels, other stands behind.",
        "**Off-the-Edge Doggy Style**—kneel over a bed or ottoman.",
        "Experiment with **Squatting Cowgirl** for deeper angle.",
        "**Tabletop**—one partner lies on a table or counter, other stands.",
        "Try **Reverse Tabletop**—facing away, lying on a surface.",
        "Go for **The Propeller**—one flat, the other at a right angle.",
        "**High-Arc Missionary**—hips elevated with a pillow, legs up.",
        "Try the **Melted Candle**—one deeply reclined, legs together and up.",
        "**Backwards Lap Dance**—heated up before full intimacy.",
        "Try a **Slow Grind Standing**—both standing, moving rhythmically.",
        "**Side-by-Side Doggy**—lying next to each other, from behind.",
        "Experiment with **Shoulder Stand**—legs resting on partner's shoulders.",
        "**The Teaser**—starters: shallow, slow moves before increasing intensity.",
        "**Foot Massage with Intimacy**—combine with sensual touch.",
        "Try the **Upside-Down**, one seated, other laying the opposite way.",
        "**Cradle Position**—one lying, the other cradled in their arms.",
        "Explore **Couch Lunge**—partner perched on the edge, other between legs.",
        "Wrap up with **Freestyle Night**—combine two or more positions in one adventure!"
    ]
};
